/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calcprog_1(char *host)
{
  CLIENT *clnt;
  in sample;
  sample.a = 10, sample.b = 20;
  int  *result_1;
  in  sumar_1_arg       = sample;
  int  *result_2;
  in restar_1_arg       = sample;
  int  *result_3;
  in  multiplicar_1_arg = sample;
  int  *result_4;
  in  dividir_1_arg     = sample;

#ifndef DEBUG
  clnt = clnt_create (host, CALCPROG, CALCVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror (host);
    exit (1);
  }
#endif  /* DEBUG */

  result_1 = sumar_1(&sumar_1_arg, clnt);
  if (result_1 == (int *) NULL) {
    clnt_perror (clnt, "call failed");
  }
  result_2 = restar_1(&restar_1_arg, clnt);
  if (result_2 == (int *) NULL) {
    clnt_perror (clnt, "call failed");
  }
  result_3 = multiplicar_1(&multiplicar_1_arg, clnt);
  if (result_3 == (int *) NULL) {
    clnt_perror (clnt, "call failed");
  }
  result_4 = dividir_1(&dividir_1_arg, clnt);
  if (result_4 == (int *) NULL) {
    clnt_perror (clnt, "call failed");
  }
  printf("Sumar = %d, Restar = %d, Multiplicar =%d, Dividir =%d\n",
        *result_1, *result_2, *result_3, *result_4);
#ifndef DEBUG
  clnt_destroy (clnt);
#endif   /* DEBUG */
}


int
main (int argc, char *argv[])
{
  char *host;

  if (argc < 2) {
    printf ("usage: %s server_host\n", argv[0]);
    exit (1);
  }
  host = argv[1];
  calcprog_1 (host);
  exit (0);
}
