/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct in {
	int a;
	int b;
};
typedef struct in in;

#define CALCPROG 0x30000001
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 0
extern  int * sumar_1(in *, CLIENT *);
extern  int * sumar_1_svc(in *, struct svc_req *);
#define restar 1
extern  int * restar_1(in *, CLIENT *);
extern  int * restar_1_svc(in *, struct svc_req *);
#define multiplicar 2
extern  int * multiplicar_1(in *, CLIENT *);
extern  int * multiplicar_1_svc(in *, struct svc_req *);
#define dividir 3
extern  int * dividir_1(in *, CLIENT *);
extern  int * dividir_1_svc(in *, struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 0
extern  int * sumar_1();
extern  int * sumar_1_svc();
#define restar 1
extern  int * restar_1();
extern  int * restar_1_svc();
#define multiplicar 2
extern  int * multiplicar_1();
extern  int * multiplicar_1_svc();
#define dividir 3
extern  int * dividir_1();
extern  int * dividir_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_in (XDR *, in*);

#else /* K&R C */
extern bool_t xdr_in ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
