/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
sumar_1_svc(in *argp, struct svc_req *rqstp)
{
  static int  result;

  /*
   * insert server code here
   */
  result = argp->a + argp->b;
  return &result;
}

int *
restar_1_svc(in *argp, struct svc_req *rqstp)
{
  static int  result;
  
  /*
   * insert server code here
   */
  result = argp->a - argp->b;
  return &result;
}

int *
multiplicar_1_svc(in *argp, struct svc_req *rqstp)
{
  static int  result;

  /*
   * insert server code here
   */
  result = argp->a * argp->b;
  return &result;
}

int *
dividir_1_svc(in *argp, struct svc_req *rqstp)
{
  static int  result;

  /*
   * insert server code here
   */
  result = argp->a / argp->b;
  return &result;
}
